name: Play the game
on:
  issues:
    types: [opened]
jobs:
  playGame:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: see event id
        run: |
          LINE=$(echo "$EVENT_ID % $(cat words.txt | wc -l) " | bc)
          echo $LINE
        env:
          EVENT_ID: ${{ github.event.issue.id }}
