name: Play the game
on:
  issues:
    types: [opened]
jobs:
  playGame:
    runs-on: ubuntu-latest
    steps:
      - name: see event id
        run: echo $EVENT_ID
        env:
          EVENT_ID: ${{ toJSON(github.event) }}
