name: Testing
on:
  workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: sudo DEBIAN_FRONTEND=noninteractive apt install -y ncal
      - name: run cal
        run: |
          cal
      
